name: Apply AI Metadata

on:
  workflow_dispatch:
    inputs:
      glob:
        description: Glob of HTML files to process
        required: false
        default: '**/*.html'

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci || npm i
      - name: Apply metadata to HTML files
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          node tools/generate-metadata.js --glob "${{ github.event.inputs.glob }}" --apply=true
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git diff --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git add -A
          git commit -m "chore: apply AI metadata"
      - name: Push changes
        run: |
          CURRENT_BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          git push origin "${CURRENT_BRANCH}"


